/**
 * ICreditResponse interface
 */
export interface ICreditResponse {
    SaleId: string
    GroupPrivateToken: string
    NumberOfItems?: string
    ItemId1?: string
    ItemCatalogNumber1?: string
    ItemQuantity1?: string
    ItemUnitPrice1?: string
    ItemDescription1?: string
    ItemId2?: string
    ItemCatalogNumber2?: string
    ItemQuantity2?: string
    ItemUnitPrice2?: string
    ItemDescription2?: string
    ItemId3?: string
    ItemCatalogNumber3?: string
    ItemQuantity3?: string
    ItemUnitPrice3?: string
    ItemDescription3?: string
    Reference?: string
    Order?: string
    CustomerLastName?: string
    CustomerFirstName?: string
    Address?: string
    POB?: string
    City?: string
    Zipcode?: string
    PhoneNumber?: string
    PhoneNumber2?: string
    FaxNumber?: string
    IdNumber?: string
    VatNumber?: string
    Custom1?: string
    Custom2?: string
    Custom3?: string
    Custom4?: string
    Custom5?: string
    Custom6?: string
    Custom7?: string
    Custom8?: string
    Custom9?: string
    CustomerId?: string
    DocumentURL?: string
    DocumentNum?: string
    DocumentType?: string
    TransactionAmount: string
    TransactionAuthNum?: string
    TransactionCardName?: string
    TransactionCardNum?: string
    TransactionCreditTerms?: string
    TransactionCreditTermsDescription?: string
    TransactionFirstAmount?: string
    TransactionNonFirstAmount?: string
    TransactionNumOfPayment?: string
    TransactionForeignSign?: string
    TransactionSolekSapak?: string
    TransactionStatus?: string
    TransactionTerminalName?: string
    TransactionTerminalNum?: string
    TransactionTransAmount?: string
    TransactionDateTime?: string
    TransactionType?: string
    TransactionTypeDescription?: string
    TransactionCurrency?: string
    TransactionCurrencyDescription?: string
    TransactionToken?: string
}
